### ISSUE TITLE
Twitter.com refusing to connect

### ISSUE THREAD

**Issue by nafizh** [austinvhuang/openmemex#6]
I saved a twitter link but in the detail section it's saying twitter.com is refusing to connect. Attaching a screenshot.
![Screenshot from 2021-11-11 13-05-09](https://user-images.githubusercontent.com/9099617/141347456-9188c30b-3ae8-4a77-b533-98f85ca5d309.png)

**Comment by austinvhuang** [comment]
Hey @nafizh ! This is because Twitter (and other sites unfortunately) block embedding a page in iframes (or any other alternative like object).

Few thoughts:
- from the gallery view you can click through to the page to see the original content, which opens the link in a tab.
- for the detail view I’ve been thinking about a few options to deal with this scenario better. One possibly is that for sites that block to replace the iframe with a high res screenshot that can be clickable to take you to the page. Another is look for a wasm browser to view the page “browserception” (but most options here are quite bleeding edge)

If you haven’t already, come join the discord if you want to discuss https://discord.gg/mGy29Smv4g !

**Comment by nafizh** [comment]
That makes sense. I think the high res image solution seems more palatable. Joined the discord server.
